version: '3.9'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/homebudget
      - JWT_SECRET=super-secret-key
      - FLASK_APP=homebudget:create_app   # ← specify factory
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homebudget
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
